### ISSUE TITLE
Set Up Repository and Environment

### ISSUE THREAD

**Issue by petternikolai** [petternikolai/project-exam-2#2]
### Sub-tasks:
- [x] Initialize GitHub repository
- [x] Set up deployment (GitHub Pages or Netlify)
- [x] Install dependencies (React w/Vite, Tailwind UI)
- [x] Organize folder structure (components, pages, services)
